### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by ghost** [ccmjs/data-server#1]
`index.js` uses deprecated code.

## 1: MongoDB connection
In `mongodb.MongoClient.connect` add the following object as second parameter to the function: `{ useNewUrlParser: true }`

## 2: Replace the following code:
- `collection.insert`=> `collection.insertOne`
- `collection.update`=> `collection.updateOne`
- `collection.remove`=> `collection.deleteOne`

**Comment by akless** [comment]
Thank's for report. The `index.js` now uses now more deprecated code.
